const app = document.getElementById('app');
const state = { user: null, query: '', page: location.hash.replace('#','') || 'login' };

const branches = ['Colombo Central','Kandy Branch','Galle Branch','Jaffna Branch','Matara Branch','Kurunegala Branch','Anuradhapura Branch','Badulla Branch'];
const categories = ['Fiction','Science','Classic Literature','History','Psychology','Memoir','Biography','Self-Help','Technology'];

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function go(page){state.page=page;location.hash=page;window.scrollTo({top:0,behavior:'smooth'});render();}
function initials(name='User'){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase() || 'U';}
function badge(text, cls=text.toLowerCase()){return `<span class="badge ${cls}">${esc(text)}</span>`}
function empty(message){return `<div class="empty-state"><strong>${esc(message)}</strong><div class="muted" style="margin-top:7px">Data will appear here after it is added through the system.</div></div>`}

function publicNav(){return `<header class="topnav"><div class="container" style="display:flex;align-items:center;width:100%"><button class="brand" style="border:0;background:none" onclick="go('home')"><span class="brand-mark">▣</span><span>Lanka Library <small class="brand-sub">PUBLIC BRANCH NETWORK</small></span></button><nav class="navlinks"><button class="navlink ${state.page==='home'?'active':''}" onclick="go('home')">Home</button><button class="navlink ${state.page==='catalogue'?'active':''}" onclick="go('catalogue')">Book Catalogue</button><button class="navlink ${state.page==='member'?'active':''}" onclick="go('member')">My Account</button></nav><div class="topnav-actions"><button class="btn btn-ghost" onclick="go('catalogue')">⌕</button>${state.user?`<button class="btn btn-ghost" onclick="go('member')"><span class="avatar">${initials(state.user.full_name)}</span>${esc(state.user.full_name)}</button><button class="btn btn-outline" onclick="logout()">Logout</button>`:`<button class="btn btn-primary" onclick="go('login')">Sign In</button>`}</div></div></header>`}

function authShell(mode='login'){const reg=mode==='register';return `<div class="auth"><section class="auth-brand"><div class="brand"><span class="brand-mark" style="background:var(--gold);color:var(--navy)">▣</span><span>Lanka Library Network<small class="brand-sub" style="display:block;color:rgba(255,255,255,.35)">PUBLIC BRANCH NETWORK · SRI LANKA</small></span></div><div class="auth-copy"><div class="eyebrow">${reg?'Member Registration':'Member Portal'}</div><h1>${reg?'Create your member account':'Knowledge without boundaries.'}</h1><p>${reg?'Register to reserve books, manage borrowing activity and access participating public library branches.':'Sign in to manage reservations, view borrowing history and browse the library catalogue.'}</p><div class="feature"><span class="check">✓</span>Centralised member account</div><div class="feature"><span class="check">✓</span>Book reservation management</div><div class="feature"><span class="check">✓</span>Branch-aware catalogue</div><div class="feature"><span class="check">✓</span>Borrowing history and notices</div></div><div class="testimonial">Your library account keeps reservations, borrowing records and branch services in one place.</div></section><section class="auth-form-wrap"><div class="auth-form"><div class="eyebrow">${reg?'Step 1 of 1':'Member Sign In'}</div><h2>${reg?'Create account':'Welcome back'}</h2>${reg?registerForm():loginForm()}<div class="auth-switch">${reg?'Already have an account?':'No account yet?'} <button onclick="go('${reg?'login':'register'}')">${reg?'Sign in':'Register free'}</button></div><div class="staff-entry"><button onclick="go('admin-login')">⚙ Staff / Librarian Login</button></div></div></section></div>`}
function loginForm(){return `<form onsubmit="login(event)"><div class="form-group"><label class="label">Email Address</label><input id="login-email" class="field" type="email" required placeholder="your@email.com"></div><div class="form-group"><label class="label">Password</label><div class="password-wrap"><input id="login-password" class="field" type="password" required placeholder="Password"><button type="button" class="toggle" onclick="togglePassword('login-password')">Show</button></div></div><div id="login-error" class="error"></div><button class="btn btn-primary" style="width:100%;padding:14px">Sign In to Account</button></form>`}
function registerForm(){return `<form onsubmit="register(event)"><div class="form-group"><label class="label">Full Name</label><input id="reg-name" class="field" required placeholder="Full name"></div><div class="form-group"><label class="label">Email Address</label><input id="reg-email" class="field" type="email" required placeholder="your@email.com"></div><div class="modal-grid"><div class="form-group"><label class="label">NIC Number</label><input id="reg-nic" class="field" placeholder="NIC number"></div><div class="form-group"><label class="label">Phone</label><input id="reg-phone" class="field" placeholder="Phone number"></div></div><div class="form-group"><label class="label">Home Branch</label><select id="reg-branch" class="field" required><option value="">Select branch</option>${branches.map(b=>`<option>${esc(b)}</option>`).join('')}</select></div><div class="form-group"><label class="label">Password</label><input id="reg-password" class="field" type="password" minlength="8" required placeholder="Minimum 8 characters"></div><div class="form-group"><label class="label">Confirm Password</label><input id="reg-confirm" class="field" type="password" minlength="8" required placeholder="Repeat password"></div><label style="display:flex;gap:8px;font-size:12px;color:#6b7280;margin-bottom:16px"><input type="checkbox" required> I agree to the Terms of Service and Privacy Policy.</label><div id="register-error" class="error"></div><button class="btn btn-primary" style="width:100%;padding:14px">Create Account</button></form>`}

function home(){return `${publicNav()}<main><section class="hero"><div class="container hero-grid"><div><div class="eyebrow">Sri Lanka Public Library Network</div><h1>Knowledge Without <span>Boundaries</span></h1><p>Search, reserve and borrow books through the public library network. Catalogue information is loaded from the library database.</p><form class="searchbar" onsubmit="searchHome(event)"><input id="home-search" placeholder="Title, author, ISBN or category..."><button>Search</button></form><div class="hero-stats"><div class="hero-stat"><strong>—</strong><span>BOOKS</span></div><div class="hero-stat"><strong>8</strong><span>BRANCHES</span></div><div class="hero-stat"><strong>—</strong><span>MEMBERS</span></div><div class="hero-stat"><strong>FREE</strong><span>ACCESS</span></div></div></div><div class="hero-book"><div style="text-align:center"><div style="font-size:40px">▣</div><div>Catalogue cover images are loaded from the database.</div></div></div></div></section><section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Explore</div><h2>Browse by Category</h2></div><button class="btn btn-outline" onclick="go('catalogue')">All categories →</button></div><div class="categories">${categories.map(c=>`<button class="category" onclick="catalogueByCategory('${esc(c)}')">▣<br><strong>${esc(c)}</strong></button>`).join('')}</div></div></section><section class="section" style="padding-top:0"><div class="container"><div class="section-head"><div><div class="eyebrow">Recently Added</div><h2>New Arrivals</h2></div><button class="btn btn-outline" onclick="go('catalogue')">Browse All →</button></div>${empty('No books have been added yet.')}</div></section><section class="section dark-section"><div class="container"><div class="section-head"><div><div class="eyebrow">Locations</div><h2 style="color:#fff">8 Branches Across Sri Lanka</h2></div></div><div class="branch-grid">${branches.map(b=>`<div class="branch">⌖ ${esc(b)}</div>`).join('')}</div></div></section></main><footer class="footer"><div class="container">Lanka Library Network · Public Branch Network · Connect the catalogue, reservations and member services through the central system.</div></footer>`}

function catalogue(){return `${publicNav()}<main class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Explore</div><h1 style="font:700 34px Lora,serif;color:var(--navy);margin:5px 0">Book Catalogue</h1><p class="muted">Search the live library catalogue.</p></div></div><div class="card" style="padding:16px;margin-bottom:18px"><form class="searchbar" style="max-width:none;margin:0;background:#f8f7f4" onsubmit="searchCatalogue(event)"><input id="catalogue-search" value="${esc(state.query)}" placeholder="Search title, author, ISBN..."><button>Search</button></form></div>${empty('No books are currently available in the catalogue.')}</div></main>`}

function member(){if(!state.user)return authShell('login');return `${publicNav()}<section class="dashboard-hero"><div class="container"><div class="dashboard-header"><div class="dashboard-title"><span class="avatar">${initials(state.user.full_name)}</span><div><div class="eyebrow">Member Dashboard</div><h1>${esc(state.user.full_name)}</h1><p>${esc(state.user.email)} · Member account</p></div></div><button class="btn btn-gold" onclick="go('catalogue')">⌕ Browse Catalogue</button></div></div></section><main class="section"><div class="container"><div class="stats"><div class="stat"><strong>0</strong><span>Total Borrowed</span></div><div class="stat"><strong>0</strong><span>Active Reservations</span></div><div class="stat"><strong>0</strong><span>Overdue Books</span></div><div class="stat"><strong>0</strong><span>Books This Month</span></div></div><div class="main-grid"><section><div class="panel"><h3>Active Reservations</h3>${empty('No active reservations.')}</div><div class="panel" style="margin-top:20px"><h3>Reading Activity</h3>${empty('No borrowing activity yet.')}</div></section><aside><div class="panel"><h3>Favourite Genres</h3>${categories.slice(0,4).map(c=>`<div style="margin:14px 0"><div style="display:flex;justify-content:space-between;font-size:12px"><span>${esc(c)}</span><span>0%</span></div><div class="progress" style="margin-top:6px"><i style="width:0"></i></div></div>`).join('')}</div><div class="panel" style="margin-top:20px"><h3>Quick Actions</h3><div class="quick-list"><button onclick="go('catalogue')">▣ Browse Catalogue →</button><button>🔖 View Reservations →</button><button>◷ Borrowing History →</button><button>♙ Edit Profile →</button></div></div></aside></div></div></main>`}

function adminLogin(){return `<div class="auth"><section class="auth-brand"><div class="brand"><span class="brand-mark" style="background:var(--gold);color:var(--navy)">▣</span><span>Lanka Library Network<small class="brand-sub" style="display:block;color:rgba(255,255,255,.35)">LIBRARIAN PANEL</small></span></div><div class="auth-copy"><div class="eyebrow">Staff Access</div><h1>Librarian control panel.</h1><p>Manage catalogue records, members, reservations and library operations from the administrative interface.</p></div><div class="testimonial">Staff authentication is separated from the member portal.</div></section><section class="auth-form-wrap"><div class="auth-form"><div class="eyebrow">Staff Login</div><h2>Welcome, Librarian</h2><form onsubmit="adminLoginSubmit(event)"><div class="form-group"><label class="label">Email Address</label><input id="admin-email" class="field" type="email" required placeholder="staff@email.com"></div><div class="form-group"><label class="label">Password</label><input id="admin-password" class="field" type="password" required placeholder="Password"></div><div id="admin-error" class="error"></div><button class="btn btn-primary" style="width:100%;padding:14px">Sign In</button></form><div class="auth-switch"><button onclick="go('login')">← Back to member login</button></div></div></section></div>`}

function admin(){return `<div class="admin-shell"><header class="admin-top"><button class="brand" style="border:0;background:none;color:#fff" onclick="go('admin')"><span class="brand-mark" style="background:var(--gold);color:var(--navy)">▣</span><span>Lanka Library <small class="brand-sub" style="display:block;color:rgba(255,255,255,.35)">LIBRARIAN PANEL</small></span></button><nav class="admin-top navlinks"><button class="navlink" style="color:#fff" onclick="adminSection('overview')">Overview</button><button class="navlink" style="color:#fff" onclick="adminSection('reservations')">Reservations</button><button class="navlink" style="color:#fff" onclick="adminSection('books')">Books</button><button class="navlink" style="color:#fff" onclick="adminSection('members')">Members</button></nav><div style="margin-left:auto;display:flex;gap:10px"><span style="font-size:12px;align-self:center">Librarian</span><button class="btn btn-outline" style="color:#fff;border-color:#fff" onclick="logout()">Logout</button></div></header><div class="admin-body"><aside class="sidebar"><div class="side-profile"><strong>Library Staff</strong><br><span class="muted">Authenticated staff</span></div><button class="side-link" onclick="adminSection('overview')">⌂ Overview</button><button class="side-link" onclick="adminSection('reservations')">🔖 Reservations</button><button class="side-link" onclick="adminSection('books')">▣ Book Catalogue</button><button class="side-link" onclick="adminSection('add-book')">＋ Add New Book</button><button class="side-link" onclick="adminSection('members')">♙ Members</button><div style="margin-top:auto"><button class="side-link" onclick="go('login')">↩ Back to Site</button></div></aside><main class="admin-content" id="admin-content"></main></div></div>`}

let adminPage='overview';
function adminSection(section){adminPage=section; if(state.page!=='admin'){state.page='admin';location.hash='admin';} render();}
function adminContent(){
  if(adminPage==='overview')return `<div class="admin-heading"><div><div class="eyebrow">${new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'})}</div><h1>Library Overview</h1></div></div><div class="admin-cards"><div class="admin-card"><strong>0</strong><span>Total Books</span></div><div class="admin-card"><strong>0</strong><span>Active Members</span></div><div class="admin-card"><strong>0</strong><span>Pending Approvals</span></div><div class="admin-card"><strong>0</strong><span>Books Overdue</span></div></div><div class="main-grid"><div class="panel"><h3>Pending Reservations</h3>${empty('No pending reservations.')}</div><div class="panel"><h3>Quick Actions</h3><div class="quick-list"><button onclick="adminSection('add-book')">＋ Add New Book</button><button onclick="adminSection('members')">♙ Register Member</button><button onclick="adminSection('books')">⌕ View Catalogue</button><button onclick="adminSection('reservations')">🔖 All Reservations</button></div></div></div>`;
  if(adminPage==='books')return `<div class="admin-heading"><div><div class="eyebrow">Manage</div><h1>Book Catalogue</h1></div><button class="btn btn-gold" onclick="adminSection('add-book')">＋ Add New Book</button></div><div class="table-wrap"><div class="toolbar"><input class="field" placeholder="Search books..."><select class="field" style="max-width:180px"><option>All Categories</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select class="field" style="max-width:160px"><option>All Status</option><option>Available</option><option>Reserved</option><option>Overdue</option></select></div><table class="table"><thead><tr><th>Book</th><th>ISBN</th><th>Category</th><th>Copies</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr><td colspan="6">${empty('No books in the catalogue.')}</td></tr></tbody></table></div>`;
  if(adminPage==='members')return `<div class="admin-heading"><div><div class="eyebrow">Manage</div><h1>Members</h1></div><button class="btn btn-gold">＋ Register Member</button></div><div class="table-wrap"><div class="toolbar"><input class="field" placeholder="Search members..."></div><table class="table"><thead><tr><th>Member</th><th>Member ID</th><th>Branch</th><th>Joined</th><th>Borrowed</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr><td colspan="7">${empty('No members registered yet.')}</td></tr></tbody></table></div>`;
  if(adminPage==='reservations')return `<div class="admin-heading"><div><div class="eyebrow">Manage</div><h1>Reservations</h1></div><button class="btn btn-outline">⇩ Export CSV</button></div><div class="table-wrap"><div class="toolbar"><button class="btn btn-primary">Pending</button><button class="btn btn-outline">Approved</button><button class="btn btn-outline">Declined</button></div><table class="table"><thead><tr><th>Reference</th><th>Member</th><th>Book</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr><td colspan="6">${empty('No reservations found.')}</td></tr></tbody></table></div>`;
  return `<div class="admin-heading"><div><div class="eyebrow">Manage</div><h1>Add New Book</h1></div></div><div class="panel"><form onsubmit="addBook(event)"><div class="modal-grid"><div class="form-group full"><label class="label">Title</label><input id="book-title" class="field" required placeholder="Book title"></div><div class="form-group"><label class="label">Author</label><input id="book-author" class="field" required placeholder="Author"></div><div class="form-group"><label class="label">ISBN</label><input id="book-isbn" class="field" placeholder="ISBN"></div><div class="form-group"><label class="label">Publisher</label><input id="book-publisher" class="field" placeholder="Publisher"></div><div class="form-group"><label class="label">Category</label><select id="book-category" class="field"><option value="">Select category</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="form-group"><label class="label">Year Published</label><input id="book-year" class="field" type="number" min="1000" max="2100"></div><div class="form-group"><label class="label">Pages</label><input id="book-pages" class="field" type="number" min="1"></div><div class="form-group"><label class="label">Number of Copies</label><input id="book-copies" class="field" type="number" min="1" value="1"></div><div class="form-group full"><label class="label">Synopsis</label><textarea id="book-synopsis" class="field" rows="5" placeholder="Enter a brief synopsis..."></textarea></div></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:10px"><button type="button" class="btn btn-outline" onclick="adminSection('books')">Cancel</button><button class="btn btn-gold">Add to Catalogue</button></div></form></div>`;
}
function render(){if(state.page==='admin') {app.innerHTML=admin();document.getElementById('admin-content').innerHTML=adminContent();return;} if(state.page==='login'){app.innerHTML=authShell('login');return}if(state.page==='register'){app.innerHTML=authShell('register');return}if(state.page==='admin-login'){app.innerHTML=adminLogin();return}if(state.page==='home'){app.innerHTML=home();return}if(state.page==='catalogue'){app.innerHTML=catalogue();return}if(state.page==='member'){app.innerHTML=member();return}app.innerHTML=home();}

async function login(e){e.preventDefault();const err=document.getElementById('login-error');err.textContent='';try{const r=await fetch('backend/auth/login.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('login-email').value,password:document.getElementById('login-password').value})});const d=await r.json();if(!d.success){err.textContent=d.message||'Login failed.';return}state.user=d.user;sessionStorage.setItem('library_user',JSON.stringify(d.user));go(d.user.role==='admin'?'admin':'home')}catch(x){err.textContent='Backend is not connected yet. Start Apache/PHP and check the API path.'}}
async function register(e){e.preventDefault();const err=document.getElementById('register-error');err.textContent='';const p=document.getElementById('reg-password').value;if(p!==document.getElementById('reg-confirm').value){err.textContent='Passwords do not match.';return}try{const r=await fetch('backend/auth/register.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({full_name:document.getElementById('reg-name').value,email:document.getElementById('reg-email').value,nic:document.getElementById('reg-nic').value,phone:document.getElementById('reg-phone').value,branch:document.getElementById('reg-branch').value,password:p})});const d=await r.json();if(!d.success){err.textContent=d.message||'Registration failed.';return}state.user=d.user;sessionStorage.setItem('library_user',JSON.stringify(d.user));go('home')}catch(x){err.textContent='Backend is not connected yet. Start Apache/PHP and check the API path.'}}
async function adminLoginSubmit(e){e.preventDefault();const err=document.getElementById('admin-error');err.textContent='';try{const r=await fetch('backend/auth/login.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('admin-email').value,password:document.getElementById('admin-password').value})});const d=await r.json();if(!d.success||d.user.role!=='admin'){err.textContent='Invalid staff credentials.';return}state.user=d.user;sessionStorage.setItem('library_user',JSON.stringify(d.user));go('admin')}catch(x){err.textContent='Backend is not connected yet. Start Apache/PHP and check the API path.'}}
async function logout(){try{await fetch('backend/auth/logout.php',{method:'POST'})}catch(e){}sessionStorage.removeItem('library_user');state.user=null;go('login')}
function togglePassword(id){const x=document.getElementById(id);x.type=x.type==='password'?'text':'password'}
function searchHome(e){e.preventDefault();state.query=document.getElementById('home-search').value;go('catalogue')}
function searchCatalogue(e){e.preventDefault();state.query=document.getElementById('catalogue-search').value;render()}
function catalogueByCategory(c){state.query=c;go('catalogue')}
function addBook(e){e.preventDefault();alert('Frontend form is ready. Connect this form to backend/books/add-book.php to persist the record in MySQL.');adminSection('books')}
window.addEventListener('hashchange',()=>{state.page=location.hash.replace('#','')||'login';render()});
try{state.user=JSON.parse(sessionStorage.getItem('library_user')||'null')}catch(e){state.user=null}
render();
